### ISSUE TITLE
Adapt to Grafana 10.3.2

### ISSUE THREAD

**Issue by penguineer** [penguineer/GrafanaScreenshots#1]
The login mask is no longer recognized.

```
Traceback (most recent call last):
File "/app/./grafanascreenshots.py", line 104, in <module>
capture_screenshot()
File "/app/./grafanascreenshots.py", line 40, in capture_screenshot
driver.find_element(By.ID, ':r0:').send_keys(username)
File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 742, in find_element
return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id=":r0:"]"}
(Session info: chrome-headless-shell=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55cc56233f83 <unknown>
#1 0x55cc55eeccf7 <unknown>
#2 0x55cc55f3c99e <unknown>
#3 0x55cc55f3caa1 <unknown>
#4 0x55cc55f87d64 <unknown>
#5 0x55cc55f660dd <unknown>
#6 0x55cc55f85006 <unknown>
#7 0x55cc55f65e53 <unknown>
#8 0x55cc55f2ddd4 <unknown>
#9 0x55cc55f2f1de <unknown>
#10 0x55cc561f8531 <unknown>
#11 0x55cc561fc455 <unknown>
#12 0x55cc561e4f55 <unknown>
#13 0x55cc561fd0ef <unknown>
#14 0x55cc561c899f <unknown>
#15 0x55cc56221008 <unknown>
#16 0x55cc562211d7 <unknown>
#17 0x55cc56233124 <unknown>
#18 0x7f6341f3cac3 <unknown>
```

**Comment by penguineer** [comment]
This is not a bug of non-matching website content, but was a problem with loading the site which has been fixed in #2
